# SELECT USER_ID
#     , PRODUCT_ID
# FROM ONLINE_SALE
# WHERE PRODUCT_ID IN (
#     SELECT PRODUCT_ID
#     FROM ONLINE_SALE
#     GROUP BY USER_ID
#     HAVING COUNT(PRODUCT_ID) > 1
# )
# ORDER BY USER_ID, PRODUCT_ID
# ;

SELECT USER_ID
    , PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID
    , PRODUCT_ID
HAVING COUNT(PRODUCT_ID) > 1
ORDER BY USER_ID ASC
    , PRODUCT_ID DESC
;