SELECT COUNT(B.ID) AS 'FISH_COUNT'
    , MAX(B.LENGTH) AS 'MAX_LENGTH'
    , B.FISH_TYPE
FROM (
    SELECT ID
        , FISH_TYPE
        , IFNULL(LENGTH, 10) AS 'LENGTH'
        , TIME
    FROM FISH_INFO A
) B
GROUP BY B.FISH_TYPE
HAVING AVG(B.LENGTH) >= 33
ORDER BY B.FISH_TYPE ASC
;